Feature/103 tutorial implementation no lists
MetaCell/NetPyNE-UI pull request #711
Opened 2023-04-14 14:59 UTC by aranega

Closes the tutorial implementation

2023-04-14 15:44 UTC, ddelpiano requested changes

2023-04-14 15:44 UTC, ddelpiano commented on webapp/components/general/TutorialJoyride.js
@enicolasgomez @aranega are we still using joyride?
if not could we clean up this and remove the library from the package.json?
Thx

2023-04-14 15:44 UTC, ddelpiano commented on webapp/package.json
> +    "node-sass": "^4.0.0",
@enicolasgomez is this a consequence of branching from development?
This should've been removed since not used anyamore

2023-04-14 15:44 UTC, ddelpiano commented on webapp/package.json
> +    "babel-plugin-transform-decorators-legacy": "^1.3.5",
@enicolasgomez is this a consequence of branching from development?
This should've been removed since not used anyamore

2023-04-14 15:44 UTC, ddelpiano commented on webapp/package.json
> +    "babel-plugin-transform-object-assign": "^6.8.0",
same here

2023-04-14 15:44 UTC, ddelpiano commented on webapp/package.json
> +    "babel-plugin-transform-runtime": "^6.15.0",
same here

2023-04-14 15:44 UTC, ddelpiano commented on webapp/package.json
> +    "casperjs": "^1.1.4",
same here

2023-04-14 15:44 UTC, ddelpiano commented on webapp/package.json
> +    "exports-loader": "^0.6.3",
same here

2023-04-14 15:44 UTC, ddelpiano commented on webapp/package.json
> +    "file-loader": "^5.1.0",
same here

2023-04-14 15:44 UTC, ddelpiano commented on webapp/package.json
> +    "imports-loader": "^0.7.1",
same here

2023-04-14 15:44 UTC, ddelpiano commented on webapp/package.json
> +    "jasmine": "^3.2.0",
same here

2023-04-14 15:44 UTC, ddelpiano commented on webapp/package.json
> +    "json-loader": "^0.5.4",
same here

2023-04-14 15:44 UTC, ddelpiano commented on webapp/package.json
> +    "slimerjs": "^1.0.0",
same here

2023-04-14 15:44 UTC, ddelpiano commented on webapp/package.json
> +    "source-map-loader": "^0.2.3",
same here

2023-04-14 15:44 UTC, ddelpiano commented on webapp/package.json
> +    "three-render-objects": ">=1.13.3",
same here

2023-04-14 15:44 UTC, ddelpiano commented on webapp/package.json
> +    "url-join": "^4.0.0",
same here

2023-04-17 12:42 UTC, enicolasgomez commented on webapp/components/general/TutorialJoyride.js
No, we are not. I removed it because it didn't fit with the requirements @aranega @ddelpiano

2023-04-17 12:54 UTC, enicolasgomez commented
@ddelpiano @aranega Fixed and pushed dependencies fix for the given branch.

2023-04-17 12:54 UTC, enicolasgomez approved these changes

2023-04-17 13:23 UTC, ddelpiano commented on webapp/package.json
> +    "file-loader": "^5.1.0",
@enicolasgomez do we need this?

2023-04-17 13:24 UTC, ddelpiano commented on webapp/package.json
> +    "exports-loader": "^0.6.3",
@enicolasgomez do we need this?

2023-04-17 13:24 UTC, ddelpiano commented on webapp/package.json
> +    "casperjs": "^1.1.4",
@enicolasgomez do we need this?

2023-04-17 13:24 UTC, ddelpiano commented on webapp/package.json
> +    "react-joyride": "^2.5.3",
@enicolasgomez joyride still present

2023-04-17 13:24 UTC, ddelpiano commented on webapp/components/general/TutorialJoyride.js
@enicolasgomez if we don't need joyride can we remove this component, please? Thx

2023-04-19 10:49 UTC, ddelpiano approved these changes

2023-04-19 10:49 UTC, merged