Feature/199 - Population cell list
MetaCell/NetPyNE-UI pull request #801
Opened 2024-01-14 08:07 UTC by D-GopalKrishna

Jira Link - [NETPYNE-199](https://metacell.atlassian.net/browse/NETPYNE-199)

Task description:
- Remove the cell List tab and Add it to the dropdown options. 
- Allow only dict/json or list(dict) as input. The video below shows the same.
    - Adds list(dict) functionality to the List component - Which accepts either - ` {'cellLabel':'gs21', 'x': 2}` or `[{'cellLabel':'gs21', 'x': 2}]`

![Screenshot 2024-01-14 132359](https://github.com/MetaCell/NetPyNE-UI/assets/59233227/0914a4ba-3b77-4a43-acdc-18121275b94c)

https://github.com/MetaCell/NetPyNE-UI/assets/59233227/d00a7826-9e7e-4257-831d-9ad9f4d08b5f

https://github.com/MetaCell/NetPyNE-UI/assets/59233227/7dc079b2-70fa-4ca8-b47c-2472542ec218

2024-01-24 18:57 UTC, SimaoBolota-MetaCell approved these changes
All Automated tests passed.

2024-01-24 19:05 UTC, enicolasgomez approved these changes

2024-01-25 09:01 UTC, ddelpiano requested changes
https://metacell.atlassian.net/browse/NETPYNE-199?focusedCommentId=13628

2024-01-25 13:25 UTC, ddelpiano approved these changes

2024-01-25 13:39 UTC, merged